### ISSUE TITLE
has no method 'gunzipSync'

### ISSUE THREAD

**Issue by danielpflood** [blvz/swiffy-convert#1]
# swiffy-convert ./*.swf

TypeError: Object #<Object> has no method 'gunzipSync'
    at Request._callback (/usr/lib/node_modules/swiffy-convert/lib/convert.js:68:14)
    at Request.self.callback (/usr/lib/node_modules/swiffy-convert/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/swiffy-convert/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/swiffy-convert/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by blvz** [comment]
What's your node version?

**Comment by danielpflood** [comment]
v0.10.33

**Comment by blvz** [comment]
It wasn't compatible with v0.10. Now it is.

**Comment by danielpflood** [comment]
Thank you!
